@echo off
REM ============================================
REM  NetSec-Forge - Clean Git History Script
REM  Run this from inside NetSec-Forge-clean folder
REM  (double-click it, or run from CMD)
REM ============================================

echo.
echo Step 1: Removing old .git folder (if any)...
if exist ".git" (
    rmdir /s /q .git
    echo    Old .git folder removed.
) else (
    echo    No .git folder found, skipping.
)

echo.
echo Step 2: Scanning files for AI-related keywords...
echo    (Copilot / Claude / ChatGPT / Generated by)
echo    Results below - review and clean manually if anything shows up:
echo ------------------------------------------------
findstr /s /i /m "copilot claude chatgpt generated" *.*
echo ------------------------------------------------
echo    Review the list above. Press any key once you've checked/cleaned files.
pause

echo.
echo Step 3: Setting git user info...
set /p GIT_NAME="Enter your Git name: "
set /p GIT_EMAIL="Enter your Git email: "
git config --global user.name "%GIT_NAME%"
git config --global user.email "%GIT_EMAIL%"

echo.
echo Step 4: Initializing fresh repository...
git init
git add .
git commit -m "Initial commit"

echo.
echo Step 5: Linking remote and force-pushing...
git remote add origin https://github.com/GLORY-2016/NetSec-Forge.git
git branch -M main
git push -f origin main

echo.
echo ============================================
echo  DONE. Remember to manually:
echo  1) Go to GitHub ^> Branches and delete any
echo     old branch other than main.
echo  2) Check the Contributors section on the
echo     repo page to confirm Copilot no longer
echo     shows up.
echo ============================================
pause
